services:

  datagen:
    image: ghcr.io/mgpradeepa/self-serv-pp:latest
    hostname: datagen
    container_name: datagen
    ports: 
      - "8086:8080"
    networks:
      - backend

  mcp-data:
    image: datagenmcp:v5
    hostname: datagenmcp
    container_name: datagenmcp
    environment: 
      APP_BASE_URL: http://datagen:8086
    depends_on:
      - datagen
    ports:
      - "8000:8080"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/tools"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 45s
    networks:
      - backend

networks:
  backend:
    driver: bridge

